[template]
src = "django.py.tmpl"
dest = "/app/jury_summons/settings/local.py"
keys = [
    "/services/postgres",
    "/aws/env",
    "/services/sqs"
]
reload_cmd = "python2 /usr/local/bin/supervisorctl -s http://localhost:9001 restart django:*"
